name: Check package size

on:
    pull_request:
        types: [ready_for_review, review_requested]

jobs:
    check_size:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - name: Get node version
              run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
              id: node
            - name: Setup node ${{ steps.node.outputs.version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ steps.node.outputs.version }}
                  cache: pnpm
            - run: pnpm install --frozen-lockfile
            - uses: preactjs/compressed-size-action@v2
              with:
                  build-script: "build"
                  pattern: "**/dist/**/*.{cjs,mjs,js}"
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
