name: Release

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - name: Get node version
              run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
              id: node
            - name: Setup node ${{ steps.node.outputs.version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ steps.node.outputs.version }}
                  cache: pnpm
            - run: pnpm install --frozen-lockfile
            - uses: changesets/action@v1
              with:
                  commit: "chore: release package(s)"
                  title: "chore: release package(s)"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
